services:
  database:
    image: "postgres"
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

volumes:
  database:
